"""Cross-language canonical test: verify Python and Rust produce identical SHA-256."""

import hashlib

from aether_py.canonical import canonical_model_json
from aether_py.models import (
    MarketKey,
    OrderIntent,
    OrderType,
    Origin,
    OriginKind,
    Quote,
    QuoteSource,
    Side,
    SizeUnit,
    TimeInForce,
    Ulid,
)


def test_cross_language_order_intent_canonical() -> None:
    """Verify Python canonical serialization matches Rust canonical_sha256.

    The expected SHA-256 hash comes from the Rust golden vector generator
    (crates/aether-core/src/bin/gen-goldens.rs) for the same deterministic
    OrderIntent value ``intent_limit_buy``.
    """
    det_ulid = Ulid("01ARZ3NDEKTSV4RRFFQ69G5FAV")
    det_ts = "2025-07-10T12:34:56.789Z"

    intent = OrderIntent(
        id=det_ulid,
        market=MarketKey("mkt:kalshi:INTC-50"),
        side=Side.buy,
        order_type=OrderType.limit,
        limit_price="0.66",
        size="10",
        size_unit=SizeUnit.contracts,
        tif=TimeInForce.gtc,
        paper=True,
        origin=Origin(
            kind=OriginKind.human,
            tier=3,
            actor_id=det_ulid,
        ),
        quote_snapshot=Quote(
            market=MarketKey("mkt:kalshi:INTC-50"),
            bid="0.65",
            ask="0.67",
            ts=det_ts,
            source=QuoteSource.stream,
        ),
        caps_version=det_ulid,
        created_ts=det_ts,
    )

    canonical = canonical_model_json(intent)
    actual_hash = hashlib.sha256(canonical.encode()).hexdigest()

    # Golden SHA-256 from Rust canonical_sha256 for this exact OrderIntent,
    # generated by gen-goldens.rs -> testdata/golden/core/order_intent.json
    expected_hash = "eab8fba2e3826847035fc598dcad0eb637c8c8d3f40afb3b36120ed7a129acf5"

    assert actual_hash == expected_hash, (
        f"Canonical SHA-256 mismatch\n"
        f"  Expected (Rust): {expected_hash}\n"
        f"  Actual (Python): {actual_hash}\n"
        f"  Canonical JSON:  {canonical}"
    )
