//! Golden vector integration tests — verify canonical bytes against stored SHA-256.
//! These tests load the golden JSON files generated by `gen-goldens` and verify
//! that canonical_json_bytes produces the same SHA-256 hash for every vector.

use aether_core::canonical::canonical_sha256;
use serde::Deserialize;
use std::fs;

#[derive(Debug, Deserialize)]
struct GoldenEntry {
    name: String,
    #[serde(rename = "type")]
    #[allow(dead_code)]
    typ: String,
    value: serde_json::Value,
    sha256: String,
}

fn load_goldens(file: &str) -> Vec<GoldenEntry> {
    // CARGO_MANIFEST_DIR = crates/aether-core, golden files at repo root
    let path = format!("{}/../../testdata/golden/core/{}", env!("CARGO_MANIFEST_DIR"), file);
    let data = fs::read_to_string(&path).unwrap_or_else(|_| panic!("read golden file: {path}"));
    serde_json::from_str(&data).unwrap_or_else(|_| panic!("parse golden file: {path}"))
}

#[test]
fn golden_money_vectors() {
    for entry in load_goldens("money.json") {
        let hash = canonical_sha256(&entry.value).unwrap();
        assert_eq!(
            hash, entry.sha256,
            "{}: SHA-256 mismatch\n  expected: {}\n  computed: {}",
            entry.name, entry.sha256, hash
        );
    }
}

#[test]
fn golden_edge_vectors() {
    for entry in load_goldens("edge.json") {
        let hash = canonical_sha256(&entry.value).unwrap();
        assert_eq!(
            hash, entry.sha256,
            "{}: SHA-256 mismatch\n  expected: {}\n  computed: {}",
            entry.name, entry.sha256, hash
        );
    }
}

#[test]
fn golden_confidence_vectors() {
    for entry in load_goldens("confidence.json") {
        let hash = canonical_sha256(&entry.value).unwrap();
        assert_eq!(hash, entry.sha256, "{}: SHA-256 mismatch", entry.name);
    }
}

#[test]
fn golden_market_key_vectors() {
    for entry in load_goldens("market_key.json") {
        let hash = canonical_sha256(&entry.value).unwrap();
        assert_eq!(hash, entry.sha256, "{}: SHA-256 mismatch", entry.name);
    }
}
